spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/distcomp'
    username: 'postgres'
    password: 'postgres'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  application:
    name: 'Spring Rest Calculator'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 24110 #or another port
springdoc:
  api-docs:
    enabled: true
    path: /api/v1.0/docs
  swagger-ui:
    path: /api/v1.0/ui-docs.html